//
// Generated by Bluespec Compiler, version 2014.03.beta2 (build 33633, 2014-03-26)
//
// On Fri Nov 21 15:38:09 EST 2014
//
//
// Ports:
// Name                         I/O  size props
// pcQ_deq_READ                   O     1
// instQ_deq_READ                 O     1
// dataReqQ_enq_READ              O    65
// dataReqQ_enq_EN_READ           O     1
// regRead_0_req_READ             O     5
// regRead_0_req_EN_READ          O     1
// regRead_1_req_READ             O     5
// regRead_1_req_EN_READ          O     1
// wbQ_enq_READ                   O    38
// wbQ_enq_EN_READ                O     1
// branchPc_READ                  O    32
// branchPc_EN_READ               O     1
// cop_write_READ                 O    37
// cop_write_EN_READ              O     1
// CLK                            I     1 unused
// RST_N                          I     1 unused
// pcQ_notEmpty_WRITE             I     1
// pcQ_first_WRITE                I    33
// instQ_notEmpty_WRITE           I     1
// instQ_first_WRITE              I    32
// dataReqQ_notFull_WRITE         I     1
// regRead_0_resp_WRITE           I    32
// regRead_1_resp_WRITE           I    32
// wbQ_notFull_WRITE              I     1
// wbIndex_WRITE                  I     5
// currEpoch_WRITE                I     1
// cop_read_WRITE                 I    32
// wbIndex_EN_WRITE               I     1
//
// Combinational paths from inputs to outputs:
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> pcQ_deq_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> instQ_deq_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    regRead_0_resp_WRITE,
//    regRead_1_resp_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> dataReqQ_enq_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> dataReqQ_enq_EN_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    regRead_0_resp_WRITE,
//    regRead_1_resp_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    cop_read_WRITE,
//    wbIndex_EN_WRITE) -> wbQ_enq_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> wbQ_enq_EN_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    regRead_0_resp_WRITE,
//    regRead_1_resp_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> branchPc_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    regRead_0_resp_WRITE,
//    regRead_1_resp_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> branchPc_EN_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    regRead_1_resp_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> cop_write_READ
//   (pcQ_notEmpty_WRITE,
//    pcQ_first_WRITE,
//    instQ_notEmpty_WRITE,
//    instQ_first_WRITE,
//    dataReqQ_notFull_WRITE,
//    wbQ_notFull_WRITE,
//    wbIndex_WRITE,
//    currEpoch_WRITE,
//    wbIndex_EN_WRITE) -> cop_write_EN_READ
//   (instQ_notEmpty_WRITE, instQ_first_WRITE) -> regRead_0_req_READ
//   instQ_notEmpty_WRITE -> regRead_0_req_EN_READ
//   (instQ_notEmpty_WRITE, instQ_first_WRITE) -> regRead_1_req_READ
//   instQ_notEmpty_WRITE -> regRead_1_req_EN_READ
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkExecute(CLK,
		 RST_N,

		 pcQ_notEmpty_WRITE,

		 pcQ_first_WRITE,

		 pcQ_deq_READ,

		 instQ_notEmpty_WRITE,

		 instQ_first_WRITE,

		 instQ_deq_READ,

		 dataReqQ_notFull_WRITE,

		 dataReqQ_enq_READ,

		 dataReqQ_enq_EN_READ,

		 regRead_0_req_READ,

		 regRead_0_req_EN_READ,

		 regRead_0_resp_WRITE,

		 regRead_1_req_READ,

		 regRead_1_req_EN_READ,

		 regRead_1_resp_WRITE,

		 wbQ_notFull_WRITE,

		 wbQ_enq_READ,

		 wbQ_enq_EN_READ,

		 wbIndex_WRITE,
		 wbIndex_EN_WRITE,

		 currEpoch_WRITE,

		 branchPc_READ,

		 branchPc_EN_READ,

		 cop_write_READ,

		 cop_write_EN_READ,

		 cop_read_WRITE);
  input  CLK;
  input  RST_N;

  // action method pcQ_notEmpty_write
  input  pcQ_notEmpty_WRITE;

  // action method pcQ_first_write
  input  [32 : 0] pcQ_first_WRITE;

  // value method pcQ_deq__read
  output pcQ_deq_READ;

  // action method instQ_notEmpty_write
  input  instQ_notEmpty_WRITE;

  // action method instQ_first_write
  input  [31 : 0] instQ_first_WRITE;

  // value method instQ_deq__read
  output instQ_deq_READ;

  // action method dataReqQ_notFull_write
  input  dataReqQ_notFull_WRITE;

  // value method dataReqQ_enq__read
  output [64 : 0] dataReqQ_enq_READ;

  // value method dataReqQ_enq_en
  output dataReqQ_enq_EN_READ;

  // value method regRead_0_req__read
  output [4 : 0] regRead_0_req_READ;

  // value method regRead_0_req_en
  output regRead_0_req_EN_READ;

  // action method regRead_0_resp_write
  input  [31 : 0] regRead_0_resp_WRITE;

  // value method regRead_1_req__read
  output [4 : 0] regRead_1_req_READ;

  // value method regRead_1_req_en
  output regRead_1_req_EN_READ;

  // action method regRead_1_resp_write
  input  [31 : 0] regRead_1_resp_WRITE;

  // action method wbQ_notFull_write
  input  wbQ_notFull_WRITE;

  // value method wbQ_enq__read
  output [37 : 0] wbQ_enq_READ;

  // value method wbQ_enq_en
  output wbQ_enq_EN_READ;

  // action method wbIndex_write
  input  [4 : 0] wbIndex_WRITE;
  input  wbIndex_EN_WRITE;

  // action method currEpoch_write
  input  currEpoch_WRITE;

  // value method branchPc__read
  output [31 : 0] branchPc_READ;

  // value method branchPc_en
  output branchPc_EN_READ;

  // value method cop_write__read
  output [36 : 0] cop_write_READ;

  // value method cop_write_en
  output cop_write_EN_READ;

  // action method cop_read_write
  input  [31 : 0] cop_read_WRITE;

  // signals for module outputs
  wire [64 : 0] dataReqQ_enq_READ;
  wire [37 : 0] wbQ_enq_READ;
  wire [36 : 0] cop_write_READ;
  wire [31 : 0] branchPc_READ;
  wire [4 : 0] regRead_0_req_READ, regRead_1_req_READ;
  wire branchPc_EN_READ,
       cop_write_EN_READ,
       dataReqQ_enq_EN_READ,
       instQ_deq_READ,
       pcQ_deq_READ,
       regRead_0_req_EN_READ,
       regRead_1_req_EN_READ,
       wbQ_enq_EN_READ;

  // ports of submodule mod__branchPc__dataLocal
  reg [31 : 0] mod__branchPc__dataLocal$IN_WRITE;
  wire [31 : 0] mod__branchPc__dataLocal$OUT_READ;
  wire mod__branchPc__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__branchPc__enLocal
  wire mod__branchPc__enLocal$IN_EN_WRITE, mod__branchPc__enLocal$OUT_READ;

  // ports of submodule mod__cop__read__dataLocal
  wire [31 : 0] mod__cop__read__dataLocal$IN_WRITE,
		mod__cop__read__dataLocal$OUT_READ;
  wire mod__cop__read__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__cop__write__dataLocal
  wire [36 : 0] mod__cop__write__dataLocal$IN_WRITE,
		mod__cop__write__dataLocal$OUT_READ;
  wire mod__cop__write__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__cop__write__enLocal
  wire mod__cop__write__enLocal$IN_EN_WRITE,
       mod__cop__write__enLocal$OUT_READ;

  // ports of submodule mod__currEpoch__dataLocal
  wire mod__currEpoch__dataLocal$IN_EN_WRITE,
       mod__currEpoch__dataLocal$IN_WRITE,
       mod__currEpoch__dataLocal$OUT_READ;

  // ports of submodule mod__dataReqQ__enq__dataLocal
  wire [64 : 0] mod__dataReqQ__enq__dataLocal$IN_WRITE,
		mod__dataReqQ__enq__dataLocal$OUT_READ;
  wire mod__dataReqQ__enq__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__dataReqQ__enq__enLocal
  wire mod__dataReqQ__enq__enLocal$IN_EN_WRITE,
       mod__dataReqQ__enq__enLocal$OUT_READ;

  // ports of submodule mod__dataReqQ__notFull__dataLocal
  wire mod__dataReqQ__notFull__dataLocal$IN_EN_WRITE,
       mod__dataReqQ__notFull__dataLocal$IN_WRITE,
       mod__dataReqQ__notFull__dataLocal$OUT_READ;

  // ports of submodule mod__instQ__deq__dataLocal
  wire mod__instQ__deq__dataLocal$IN_EN_WRITE,
       mod__instQ__deq__dataLocal$OUT_READ;

  // ports of submodule mod__instQ__first__dataLocal
  wire [31 : 0] mod__instQ__first__dataLocal$IN_WRITE,
		mod__instQ__first__dataLocal$OUT_READ;
  wire mod__instQ__first__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__instQ__notEmpty__dataLocal
  wire mod__instQ__notEmpty__dataLocal$IN_EN_WRITE,
       mod__instQ__notEmpty__dataLocal$IN_WRITE,
       mod__instQ__notEmpty__dataLocal$OUT_READ;

  // ports of submodule mod__pcQ__deq__dataLocal
  wire mod__pcQ__deq__dataLocal$IN_EN_WRITE,
       mod__pcQ__deq__dataLocal$OUT_READ;

  // ports of submodule mod__pcQ__first__dataLocal
  wire [32 : 0] mod__pcQ__first__dataLocal$IN_WRITE,
		mod__pcQ__first__dataLocal$OUT_READ;
  wire mod__pcQ__first__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__pcQ__notEmpty__dataLocal
  wire mod__pcQ__notEmpty__dataLocal$IN_EN_WRITE,
       mod__pcQ__notEmpty__dataLocal$IN_WRITE,
       mod__pcQ__notEmpty__dataLocal$OUT_READ;

  // ports of submodule mod__regRead__0_req__dataLocal
  wire [4 : 0] mod__regRead__0_req__dataLocal$IN_WRITE,
	       mod__regRead__0_req__dataLocal$OUT_READ;
  wire mod__regRead__0_req__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__regRead__0_req__enLocal
  wire mod__regRead__0_req__enLocal$IN_EN_WRITE,
       mod__regRead__0_req__enLocal$OUT_READ;

  // ports of submodule mod__regRead__0_resp__dataLocal
  wire [31 : 0] mod__regRead__0_resp__dataLocal$IN_WRITE,
		mod__regRead__0_resp__dataLocal$OUT_READ;
  wire mod__regRead__0_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__regRead__1_req__dataLocal
  wire [4 : 0] mod__regRead__1_req__dataLocal$IN_WRITE,
	       mod__regRead__1_req__dataLocal$OUT_READ;
  wire mod__regRead__1_req__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__regRead__1_req__enLocal
  wire mod__regRead__1_req__enLocal$IN_EN_WRITE,
       mod__regRead__1_req__enLocal$OUT_READ;

  // ports of submodule mod__regRead__1_resp__dataLocal
  wire [31 : 0] mod__regRead__1_resp__dataLocal$IN_WRITE,
		mod__regRead__1_resp__dataLocal$OUT_READ;
  wire mod__regRead__1_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__wbIndex__dataLocal
  wire [4 : 0] mod__wbIndex__dataLocal$IN_WRITE,
	       mod__wbIndex__dataLocal$OUT_READ;
  wire mod__wbIndex__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__wbIndex__enLocal
  wire mod__wbIndex__enLocal$IN_EN_WRITE, mod__wbIndex__enLocal$OUT_READ;

  // ports of submodule mod__wbQ__enq__dataLocal
  wire [37 : 0] mod__wbQ__enq__dataLocal$IN_WRITE,
		mod__wbQ__enq__dataLocal$OUT_READ;
  wire mod__wbQ__enq__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__wbQ__enq__enLocal
  wire mod__wbQ__enq__enLocal$IN_EN_WRITE, mod__wbQ__enq__enLocal$OUT_READ;

  // ports of submodule mod__wbQ__notFull__dataLocal
  wire mod__wbQ__notFull__dataLocal$IN_EN_WRITE,
       mod__wbQ__notFull__dataLocal$IN_WRITE,
       mod__wbQ__notFull__dataLocal$OUT_READ;

  // rule scheduling signals
  wire WILL_FIRE_RL_r2;

  // remaining internal signals
  reg [31 : 0] IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269,
	       IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261;
  reg [4 : 0] x__h20298;
  reg CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q1,
      CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q2,
      CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q3,
      CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q4,
      CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q5,
      IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d143,
      IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d290;
  wire [31 : 0] IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d273,
		b__h4488,
		b__h4561,
		b__h4598,
		b__h4639,
		b__h4677,
		b__h4753,
		b__h4792,
		branchTarget__h4334,
		imm__h20554,
		ret__h20629,
		ret__h25269,
		ret__h25305,
		ret__h25341,
		ret__h29484,
		ret__h29516,
		ret__h29548,
		ret__h29643,
		ret__h29753,
		ret__h29821,
		ret__h29890,
		ret__h29985,
		ret__h30053,
		ret__h30122,
		ret__h30154,
		ret__h30186,
		ret__h30218,
		ret__h30250,
		ret__h30282,
		ret__h30326,
		ret__h30362,
		zimm__h20555;
  wire IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d103,
       IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d129,
       IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d153,
       IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159,
       IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d322,
       IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d324,
       mod__instQ__first__dataLocal__read_BITS_20_TO__ETC___d332,
       mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d124,
       mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d156,
       mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d180,
       mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d294,
       mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d320,
       mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9,
       mod__regRead__0_resp__dataLocal__read__92_EQ_m_ETC___d275,
       mod__regRead__0_resp__dataLocal__read__92_SLE_0___d280,
       mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d101,
       mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d63;

  // value method pcQ_deq__read
  assign pcQ_deq_READ = mod__pcQ__deq__dataLocal$OUT_READ ;

  // value method instQ_deq__read
  assign instQ_deq_READ = mod__instQ__deq__dataLocal$OUT_READ ;

  // value method dataReqQ_enq__read
  assign dataReqQ_enq_READ = mod__dataReqQ__enq__dataLocal$OUT_READ ;

  // value method dataReqQ_enq_en
  assign dataReqQ_enq_EN_READ = mod__dataReqQ__enq__enLocal$OUT_READ ;

  // value method regRead_0_req__read
  assign regRead_0_req_READ = mod__regRead__0_req__dataLocal$OUT_READ ;

  // value method regRead_0_req_en
  assign regRead_0_req_EN_READ = mod__regRead__0_req__enLocal$OUT_READ ;

  // value method regRead_1_req__read
  assign regRead_1_req_READ = mod__regRead__1_req__dataLocal$OUT_READ ;

  // value method regRead_1_req_en
  assign regRead_1_req_EN_READ = mod__regRead__1_req__enLocal$OUT_READ ;

  // value method wbQ_enq__read
  assign wbQ_enq_READ = mod__wbQ__enq__dataLocal$OUT_READ ;

  // value method wbQ_enq_en
  assign wbQ_enq_EN_READ = mod__wbQ__enq__enLocal$OUT_READ ;

  // value method branchPc__read
  assign branchPc_READ = mod__branchPc__dataLocal$OUT_READ ;

  // value method branchPc_en
  assign branchPc_EN_READ = mod__branchPc__enLocal$OUT_READ ;

  // value method cop_write__read
  assign cop_write_READ = mod__cop__write__dataLocal$OUT_READ ;

  // value method cop_write_en
  assign cop_write_EN_READ = mod__cop__write__enLocal$OUT_READ ;

  // submodule mod__branchPc__dataLocal
  mkWire #( /*width*/ 32'd32) mod__branchPc__dataLocal(.IN_WRITE(mod__branchPc__dataLocal$IN_WRITE),
						       .IN_EN_WRITE(mod__branchPc__dataLocal$IN_EN_WRITE),
						       .OUT_READ(mod__branchPc__dataLocal$OUT_READ));

  // submodule mod__branchPc__enLocal
  mkPulse mod__branchPc__enLocal(.IN_EN_WRITE(mod__branchPc__enLocal$IN_EN_WRITE),
				 .OUT_READ(mod__branchPc__enLocal$OUT_READ));

  // submodule mod__cop__read__dataLocal
  mkWire #( /*width*/ 32'd32) mod__cop__read__dataLocal(.IN_WRITE(mod__cop__read__dataLocal$IN_WRITE),
							.IN_EN_WRITE(mod__cop__read__dataLocal$IN_EN_WRITE),
							.OUT_READ(mod__cop__read__dataLocal$OUT_READ));

  // submodule mod__cop__write__dataLocal
  mkWire #( /*width*/ 32'd37) mod__cop__write__dataLocal(.IN_WRITE(mod__cop__write__dataLocal$IN_WRITE),
							 .IN_EN_WRITE(mod__cop__write__dataLocal$IN_EN_WRITE),
							 .OUT_READ(mod__cop__write__dataLocal$OUT_READ));

  // submodule mod__cop__write__enLocal
  mkPulse mod__cop__write__enLocal(.IN_EN_WRITE(mod__cop__write__enLocal$IN_EN_WRITE),
				   .OUT_READ(mod__cop__write__enLocal$OUT_READ));

  // submodule mod__currEpoch__dataLocal
  mkWire #( /*width*/ 32'd1) mod__currEpoch__dataLocal(.IN_WRITE(mod__currEpoch__dataLocal$IN_WRITE),
						       .IN_EN_WRITE(mod__currEpoch__dataLocal$IN_EN_WRITE),
						       .OUT_READ(mod__currEpoch__dataLocal$OUT_READ));

  // submodule mod__dataReqQ__enq__dataLocal
  mkWire #( /*width*/ 32'd65) mod__dataReqQ__enq__dataLocal(.IN_WRITE(mod__dataReqQ__enq__dataLocal$IN_WRITE),
							    .IN_EN_WRITE(mod__dataReqQ__enq__dataLocal$IN_EN_WRITE),
							    .OUT_READ(mod__dataReqQ__enq__dataLocal$OUT_READ));

  // submodule mod__dataReqQ__enq__enLocal
  mkPulse mod__dataReqQ__enq__enLocal(.IN_EN_WRITE(mod__dataReqQ__enq__enLocal$IN_EN_WRITE),
				      .OUT_READ(mod__dataReqQ__enq__enLocal$OUT_READ));

  // submodule mod__dataReqQ__notFull__dataLocal
  mkWire #( /*width*/ 32'd1) mod__dataReqQ__notFull__dataLocal(.IN_WRITE(mod__dataReqQ__notFull__dataLocal$IN_WRITE),
							       .IN_EN_WRITE(mod__dataReqQ__notFull__dataLocal$IN_EN_WRITE),
							       .OUT_READ(mod__dataReqQ__notFull__dataLocal$OUT_READ));

  // submodule mod__instQ__deq__dataLocal
  mkPulse mod__instQ__deq__dataLocal(.IN_EN_WRITE(mod__instQ__deq__dataLocal$IN_EN_WRITE),
				     .OUT_READ(mod__instQ__deq__dataLocal$OUT_READ));

  // submodule mod__instQ__first__dataLocal
  mkWire #( /*width*/ 32'd32) mod__instQ__first__dataLocal(.IN_WRITE(mod__instQ__first__dataLocal$IN_WRITE),
							   .IN_EN_WRITE(mod__instQ__first__dataLocal$IN_EN_WRITE),
							   .OUT_READ(mod__instQ__first__dataLocal$OUT_READ));

  // submodule mod__instQ__notEmpty__dataLocal
  mkWire #( /*width*/ 32'd1) mod__instQ__notEmpty__dataLocal(.IN_WRITE(mod__instQ__notEmpty__dataLocal$IN_WRITE),
							     .IN_EN_WRITE(mod__instQ__notEmpty__dataLocal$IN_EN_WRITE),
							     .OUT_READ(mod__instQ__notEmpty__dataLocal$OUT_READ));

  // submodule mod__pcQ__deq__dataLocal
  mkPulse mod__pcQ__deq__dataLocal(.IN_EN_WRITE(mod__pcQ__deq__dataLocal$IN_EN_WRITE),
				   .OUT_READ(mod__pcQ__deq__dataLocal$OUT_READ));

  // submodule mod__pcQ__first__dataLocal
  mkWire #( /*width*/ 32'd33) mod__pcQ__first__dataLocal(.IN_WRITE(mod__pcQ__first__dataLocal$IN_WRITE),
							 .IN_EN_WRITE(mod__pcQ__first__dataLocal$IN_EN_WRITE),
							 .OUT_READ(mod__pcQ__first__dataLocal$OUT_READ));

  // submodule mod__pcQ__notEmpty__dataLocal
  mkWire #( /*width*/ 32'd1) mod__pcQ__notEmpty__dataLocal(.IN_WRITE(mod__pcQ__notEmpty__dataLocal$IN_WRITE),
							   .IN_EN_WRITE(mod__pcQ__notEmpty__dataLocal$IN_EN_WRITE),
							   .OUT_READ(mod__pcQ__notEmpty__dataLocal$OUT_READ));

  // submodule mod__regRead__0_req__dataLocal
  mkWire #( /*width*/ 32'd5) mod__regRead__0_req__dataLocal(.IN_WRITE(mod__regRead__0_req__dataLocal$IN_WRITE),
							    .IN_EN_WRITE(mod__regRead__0_req__dataLocal$IN_EN_WRITE),
							    .OUT_READ(mod__regRead__0_req__dataLocal$OUT_READ));

  // submodule mod__regRead__0_req__enLocal
  mkPulse mod__regRead__0_req__enLocal(.IN_EN_WRITE(mod__regRead__0_req__enLocal$IN_EN_WRITE),
				       .OUT_READ(mod__regRead__0_req__enLocal$OUT_READ));

  // submodule mod__regRead__0_resp__dataLocal
  mkWire #( /*width*/ 32'd32) mod__regRead__0_resp__dataLocal(.IN_WRITE(mod__regRead__0_resp__dataLocal$IN_WRITE),
							      .IN_EN_WRITE(mod__regRead__0_resp__dataLocal$IN_EN_WRITE),
							      .OUT_READ(mod__regRead__0_resp__dataLocal$OUT_READ));

  // submodule mod__regRead__1_req__dataLocal
  mkWire #( /*width*/ 32'd5) mod__regRead__1_req__dataLocal(.IN_WRITE(mod__regRead__1_req__dataLocal$IN_WRITE),
							    .IN_EN_WRITE(mod__regRead__1_req__dataLocal$IN_EN_WRITE),
							    .OUT_READ(mod__regRead__1_req__dataLocal$OUT_READ));

  // submodule mod__regRead__1_req__enLocal
  mkPulse mod__regRead__1_req__enLocal(.IN_EN_WRITE(mod__regRead__1_req__enLocal$IN_EN_WRITE),
				       .OUT_READ(mod__regRead__1_req__enLocal$OUT_READ));

  // submodule mod__regRead__1_resp__dataLocal
  mkWire #( /*width*/ 32'd32) mod__regRead__1_resp__dataLocal(.IN_WRITE(mod__regRead__1_resp__dataLocal$IN_WRITE),
							      .IN_EN_WRITE(mod__regRead__1_resp__dataLocal$IN_EN_WRITE),
							      .OUT_READ(mod__regRead__1_resp__dataLocal$OUT_READ));

  // submodule mod__wbIndex__dataLocal
  mkWire #( /*width*/ 32'd5) mod__wbIndex__dataLocal(.IN_WRITE(mod__wbIndex__dataLocal$IN_WRITE),
						     .IN_EN_WRITE(mod__wbIndex__dataLocal$IN_EN_WRITE),
						     .OUT_READ(mod__wbIndex__dataLocal$OUT_READ));

  // submodule mod__wbIndex__enLocal
  mkPulse mod__wbIndex__enLocal(.IN_EN_WRITE(mod__wbIndex__enLocal$IN_EN_WRITE),
				.OUT_READ(mod__wbIndex__enLocal$OUT_READ));

  // submodule mod__wbQ__enq__dataLocal
  mkWire #( /*width*/ 32'd38) mod__wbQ__enq__dataLocal(.IN_WRITE(mod__wbQ__enq__dataLocal$IN_WRITE),
						       .IN_EN_WRITE(mod__wbQ__enq__dataLocal$IN_EN_WRITE),
						       .OUT_READ(mod__wbQ__enq__dataLocal$OUT_READ));

  // submodule mod__wbQ__enq__enLocal
  mkPulse mod__wbQ__enq__enLocal(.IN_EN_WRITE(mod__wbQ__enq__enLocal$IN_EN_WRITE),
				 .OUT_READ(mod__wbQ__enq__enLocal$OUT_READ));

  // submodule mod__wbQ__notFull__dataLocal
  mkWire #( /*width*/ 32'd1) mod__wbQ__notFull__dataLocal(.IN_WRITE(mod__wbQ__notFull__dataLocal$IN_WRITE),
							  .IN_EN_WRITE(mod__wbQ__notFull__dataLocal$IN_EN_WRITE),
							  .OUT_READ(mod__wbQ__notFull__dataLocal$OUT_READ));

  // rule RL_r2
  assign WILL_FIRE_RL_r2 =
	     mod__instQ__notEmpty__dataLocal$OUT_READ &&
	     mod__pcQ__notEmpty__dataLocal$OUT_READ &&
	     (!mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 ||
	      IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d103 ||
	      mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d124 &&
	      IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d129) ;

  // submodule mod__branchPc__dataLocal
  always@(mod__instQ__first__dataLocal$OUT_READ or
	  b__h4753 or
	  b__h4792 or
	  mod__regRead__0_resp__dataLocal$OUT_READ or
	  b__h4488 or b__h4561 or b__h4598 or b__h4639 or b__h4677)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b0:
	  mod__branchPc__dataLocal$IN_WRITE =
	      mod__regRead__0_resp__dataLocal$OUT_READ;
      6'b000010, 6'b000011: mod__branchPc__dataLocal$IN_WRITE = b__h4488;
      6'b000100: mod__branchPc__dataLocal$IN_WRITE = b__h4561;
      6'b000101: mod__branchPc__dataLocal$IN_WRITE = b__h4598;
      6'b000110: mod__branchPc__dataLocal$IN_WRITE = b__h4639;
      6'b000111: mod__branchPc__dataLocal$IN_WRITE = b__h4677;
      default: mod__branchPc__dataLocal$IN_WRITE =
		   (mod__instQ__first__dataLocal$OUT_READ[20:16] == 5'd0) ?
		     b__h4753 :
		     b__h4792;
    endcase
  end
  assign mod__branchPc__dataLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159 &&
	     mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d294 ;

  // submodule mod__branchPc__enLocal
  assign mod__branchPc__enLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159 &&
	     mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d294 ;

  // submodule mod__cop__read__dataLocal
  assign mod__cop__read__dataLocal$IN_WRITE = cop_read_WRITE ;
  assign mod__cop__read__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__cop__write__dataLocal
  assign mod__cop__write__dataLocal$IN_WRITE =
	     { mod__instQ__first__dataLocal$OUT_READ[15:11],
	       mod__regRead__1_resp__dataLocal$OUT_READ } ;
  assign mod__cop__write__dataLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     mod__instQ__first__dataLocal__read_BITS_20_TO__ETC___d332 ;

  // submodule mod__cop__write__enLocal
  assign mod__cop__write__enLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     mod__instQ__first__dataLocal__read_BITS_20_TO__ETC___d332 ;

  // submodule mod__currEpoch__dataLocal
  assign mod__currEpoch__dataLocal$IN_WRITE = currEpoch_WRITE ;
  assign mod__currEpoch__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__dataReqQ__enq__dataLocal
  assign mod__dataReqQ__enq__dataLocal$IN_WRITE =
	     { mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b100011,
	       (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b100011) ?
		 {2{IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269}} :
		 { IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269,
		   mod__regRead__1_resp__dataLocal$OUT_READ } } ;
  assign mod__dataReqQ__enq__dataLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d324 ;

  // submodule mod__dataReqQ__enq__enLocal
  assign mod__dataReqQ__enq__enLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d324 ;

  // submodule mod__dataReqQ__notFull__dataLocal
  assign mod__dataReqQ__notFull__dataLocal$IN_WRITE = dataReqQ_notFull_WRITE ;
  assign mod__dataReqQ__notFull__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__instQ__deq__dataLocal
  assign mod__instQ__deq__dataLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     (IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159 ||
	      !mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9) ;

  // submodule mod__instQ__first__dataLocal
  assign mod__instQ__first__dataLocal$IN_WRITE = instQ_first_WRITE ;
  assign mod__instQ__first__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__instQ__notEmpty__dataLocal
  assign mod__instQ__notEmpty__dataLocal$IN_WRITE = instQ_notEmpty_WRITE ;
  assign mod__instQ__notEmpty__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__pcQ__deq__dataLocal
  assign mod__pcQ__deq__dataLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     (IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159 ||
	      !mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9) ;

  // submodule mod__pcQ__first__dataLocal
  assign mod__pcQ__first__dataLocal$IN_WRITE = pcQ_first_WRITE ;
  assign mod__pcQ__first__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__pcQ__notEmpty__dataLocal
  assign mod__pcQ__notEmpty__dataLocal$IN_WRITE = pcQ_notEmpty_WRITE ;
  assign mod__pcQ__notEmpty__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regRead__0_req__dataLocal
  assign mod__regRead__0_req__dataLocal$IN_WRITE =
	     mod__instQ__first__dataLocal$OUT_READ[25:21] ;
  assign mod__regRead__0_req__dataLocal$IN_EN_WRITE =
	     mod__instQ__notEmpty__dataLocal$OUT_READ ;

  // submodule mod__regRead__0_req__enLocal
  assign mod__regRead__0_req__enLocal$IN_EN_WRITE =
	     mod__instQ__notEmpty__dataLocal$OUT_READ ;

  // submodule mod__regRead__0_resp__dataLocal
  assign mod__regRead__0_resp__dataLocal$IN_WRITE = regRead_0_resp_WRITE ;
  assign mod__regRead__0_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__regRead__1_req__dataLocal
  assign mod__regRead__1_req__dataLocal$IN_WRITE =
	     mod__instQ__first__dataLocal$OUT_READ[20:16] ;
  assign mod__regRead__1_req__dataLocal$IN_EN_WRITE =
	     mod__instQ__notEmpty__dataLocal$OUT_READ ;

  // submodule mod__regRead__1_req__enLocal
  assign mod__regRead__1_req__enLocal$IN_EN_WRITE =
	     mod__instQ__notEmpty__dataLocal$OUT_READ ;

  // submodule mod__regRead__1_resp__dataLocal
  assign mod__regRead__1_resp__dataLocal$IN_WRITE = regRead_1_resp_WRITE ;
  assign mod__regRead__1_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__wbIndex__dataLocal
  assign mod__wbIndex__dataLocal$IN_WRITE = wbIndex_WRITE ;
  assign mod__wbIndex__dataLocal$IN_EN_WRITE = wbIndex_EN_WRITE ;

  // submodule mod__wbIndex__enLocal
  assign mod__wbIndex__enLocal$IN_EN_WRITE = wbIndex_EN_WRITE ;

  // submodule mod__wbQ__enq__dataLocal
  assign mod__wbQ__enq__dataLocal$IN_WRITE =
	     { x__h20298,
	       mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b100011,
	       IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d273 } ;
  assign mod__wbQ__enq__dataLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159 &&
	     mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d180 ;

  // submodule mod__wbQ__enq__enLocal
  assign mod__wbQ__enq__enLocal$IN_EN_WRITE =
	     WILL_FIRE_RL_r2 &&
	     mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 &&
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159 &&
	     mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d180 ;

  // submodule mod__wbQ__notFull__dataLocal
  assign mod__wbQ__notFull__dataLocal$IN_WRITE = wbQ_notFull_WRITE ;
  assign mod__wbQ__notFull__dataLocal$IN_EN_WRITE = 1'd1 ;

  // remaining internal signals
  assign IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d103 =
	     CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q2 &&
	     mod__wbIndex__enLocal$OUT_READ &&
	     mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d63 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b100011 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b001001 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b001010 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b001011 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b001100 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b001101 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b001110 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b001111 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000010 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000011 &&
	     ((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0) ?
		CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q3 :
		mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000110 &&
		mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000111 &&
		mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000001 &&
		((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b010000) ?
		   mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b0 &&
		   mod__instQ__first__dataLocal$OUT_READ[20:16] != 5'd0 :
		   mod__instQ__first__dataLocal$OUT_READ[20:16] != 5'd0)) &&
	     mod__wbIndex__enLocal$OUT_READ &&
	     mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d101 ;
  assign IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d129 =
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000010 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000100 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000101 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000110 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000111 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000001 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0 &&
	      (mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001000 ||
	       mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001001)) ?
	       ((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0) ?
		  mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001000 :
		  mod__instQ__first__dataLocal$OUT_READ[31:26] !=
		  6'b000011) ||
	       mod__wbQ__notFull__dataLocal$OUT_READ :
	       mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b100011 ||
	       mod__dataReqQ__notFull__dataLocal$OUT_READ &&
	       mod__wbQ__notFull__dataLocal$OUT_READ ;
  assign IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d153 =
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0) ?
	       CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q5 :
	       mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000110 ||
	       mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000111 ||
	       mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000001 ||
	       ((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b010000) ?
		  mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0 ||
		  mod__instQ__first__dataLocal$OUT_READ[20:16] == 5'd0 :
		  mod__instQ__first__dataLocal$OUT_READ[20:16] == 5'd0) ;
  assign IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d159 =
	     (IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d143 ||
	      !mod__wbIndex__enLocal$OUT_READ ||
	      !mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d63) &&
	     (mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d156 ||
	      !mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d101) ;
  assign IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d273 =
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000010 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000100 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000101 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000110 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000111 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000001 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0 &&
	      (mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001000 ||
	       mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001001)) ?
	       mod__pcQ__first__dataLocal$OUT_READ[32:1] :
	       ((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b010000 &&
		 mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0) ?
		  mod__cop__read__dataLocal$OUT_READ :
		  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269) ;
  assign IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d322 =
	     (IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d143 ||
	      !mod__wbIndex__enLocal$OUT_READ ||
	      !mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d63) &&
	     (mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d320 ||
	      !mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d101) ;
  assign IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d324 =
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d322 &&
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b100011 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b101011) ;
  assign b__h4488 =
	     { mod__pcQ__first__dataLocal$OUT_READ[32:29],
	       mod__instQ__first__dataLocal$OUT_READ[25:0],
	       2'b0 } ;
  assign b__h4561 =
	     mod__regRead__0_resp__dataLocal__read__92_EQ_m_ETC___d275 ?
	       branchTarget__h4334 :
	       mod__pcQ__first__dataLocal$OUT_READ[32:1] ;
  assign b__h4598 =
	     mod__regRead__0_resp__dataLocal__read__92_EQ_m_ETC___d275 ?
	       mod__pcQ__first__dataLocal$OUT_READ[32:1] :
	       branchTarget__h4334 ;
  assign b__h4639 =
	     (mod__regRead__0_resp__dataLocal$OUT_READ == 32'd0 ||
	      mod__regRead__0_resp__dataLocal$OUT_READ[31]) ?
	       branchTarget__h4334 :
	       mod__pcQ__first__dataLocal$OUT_READ[32:1] ;
  assign b__h4677 =
	     mod__regRead__0_resp__dataLocal__read__92_SLE_0___d280 ?
	       mod__pcQ__first__dataLocal$OUT_READ[32:1] :
	       branchTarget__h4334 ;
  assign b__h4753 =
	     mod__regRead__0_resp__dataLocal$OUT_READ[31] ?
	       branchTarget__h4334 :
	       mod__pcQ__first__dataLocal$OUT_READ[32:1] ;
  assign b__h4792 =
	     mod__regRead__0_resp__dataLocal$OUT_READ[31] ?
	       mod__pcQ__first__dataLocal$OUT_READ[32:1] :
	       branchTarget__h4334 ;
  assign branchTarget__h4334 =
	     mod__pcQ__first__dataLocal$OUT_READ[32:1] +
	     { mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15:0],
	       2'd0 } ;
  assign imm__h20554 =
	     { mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15],
	       mod__instQ__first__dataLocal$OUT_READ[15:0] } ;
  assign mod__instQ__first__dataLocal__read_BITS_20_TO__ETC___d332 =
	     (mod__instQ__first__dataLocal$OUT_READ[20:16] == 5'd0 ||
	      !mod__wbIndex__enLocal$OUT_READ ||
	      !mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d101) &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b010000 &&
	     mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b00100 ;
  assign mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d124 =
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000010 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000100 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000101 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000110 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000111 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000001 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0 &&
	     (mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001000 ||
	      mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001001) ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b100011 ||
	     ((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b101011) ?
		mod__dataReqQ__notFull__dataLocal$OUT_READ :
		((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b010000 &&
		  mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0) ?
		   mod__wbQ__notFull__dataLocal$OUT_READ :
		   mod__instQ__first__dataLocal$OUT_READ[31:26] ==
		   6'b010000 &&
		   mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b00100 ||
		   mod__wbQ__notFull__dataLocal$OUT_READ)) ;
  assign mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d156 =
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b100011 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001001 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001010 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001011 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001100 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001101 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001110 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001111 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000010 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011 ||
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d153 ||
	     !mod__wbIndex__enLocal$OUT_READ ;
  assign mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d180 =
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000010 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000100 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000101 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000110 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000111 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000001 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0 &&
	      (mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001000 ||
	       mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001001)) &&
	     ((mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0) ?
		mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b001000 :
		mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011) ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000010 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000011 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000100 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000101 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000110 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000111 &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b000001 &&
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b0 ||
	      mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b001000 &&
	      mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b001001) &&
	     mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b101011 &&
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] != 6'b010000 ||
	      mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b00100) ;
  assign mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d294 =
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000010 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000100 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000101 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000110 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000111 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000001 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0 &&
	      (mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001000 ||
	       mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001001)) &&
	     (mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b0 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000010 ||
	      mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b000011 ||
	      IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d290) ;
  assign mod__instQ__first__dataLocal__read_BITS_31_TO__ETC___d320 =
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b100011 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001001 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001010 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001011 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001100 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001101 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001110 ||
	     mod__instQ__first__dataLocal$OUT_READ[31:26] == 6'b001111 ||
	     IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d153 ||
	     !mod__wbIndex__enLocal$OUT_READ ;
  assign mod__pcQ__first__dataLocal__read_BIT_0_EQ_mod__ETC___d9 =
	     mod__pcQ__first__dataLocal$OUT_READ[0] ==
	     mod__currEpoch__dataLocal$OUT_READ ;
  assign mod__regRead__0_resp__dataLocal__read__92_EQ_m_ETC___d275 =
	     mod__regRead__0_resp__dataLocal$OUT_READ ==
	     mod__regRead__1_resp__dataLocal$OUT_READ ;
  assign mod__regRead__0_resp__dataLocal__read__92_SLE_0___d280 =
	     (mod__regRead__0_resp__dataLocal$OUT_READ ^ 32'h80000000) <=
	     32'h80000000 ;
  assign mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d101 =
	     mod__wbIndex__dataLocal$OUT_READ ==
	     mod__instQ__first__dataLocal$OUT_READ[20:16] ;
  assign mod__wbIndex__dataLocal__read__2_EQ_mod__instQ_ETC___d63 =
	     mod__wbIndex__dataLocal$OUT_READ ==
	     mod__instQ__first__dataLocal$OUT_READ[25:21] ;
  assign ret__h20629 =
	     mod__regRead__0_resp__dataLocal$OUT_READ + imm__h20554 ;
  assign ret__h25269 =
	     ((mod__regRead__0_resp__dataLocal$OUT_READ ^ 32'h80000000) <
	      (imm__h20554 ^ 32'h80000000)) ?
	       32'd1 :
	       32'd0 ;
  assign ret__h25305 =
	     (mod__regRead__0_resp__dataLocal$OUT_READ < imm__h20554) ?
	       32'd1 :
	       32'd0 ;
  assign ret__h25341 =
	     mod__regRead__0_resp__dataLocal$OUT_READ & zimm__h20555 ;
  assign ret__h29484 =
	     mod__regRead__0_resp__dataLocal$OUT_READ | zimm__h20555 ;
  assign ret__h29516 =
	     mod__regRead__0_resp__dataLocal$OUT_READ ^ zimm__h20555 ;
  assign ret__h29548 =
	     { mod__instQ__first__dataLocal$OUT_READ[15:0], 16'b0 } ;
  assign ret__h29643 =
	     mod__regRead__1_resp__dataLocal$OUT_READ <<
	     mod__instQ__first__dataLocal$OUT_READ[10:6] ;
  assign ret__h29753 =
	     mod__regRead__1_resp__dataLocal$OUT_READ >>
	     mod__instQ__first__dataLocal$OUT_READ[10:6] ;
  assign ret__h29821 =
	     mod__regRead__1_resp__dataLocal$OUT_READ >>
	     mod__instQ__first__dataLocal$OUT_READ[10:6] |
	     ~(32'hFFFFFFFF >> mod__instQ__first__dataLocal$OUT_READ[10:6]) &
	     {32{mod__regRead__1_resp__dataLocal$OUT_READ[31]}} ;
  assign ret__h29890 =
	     mod__regRead__1_resp__dataLocal$OUT_READ <<
	     mod__regRead__0_resp__dataLocal$OUT_READ[4:0] ;
  assign ret__h29985 =
	     mod__regRead__1_resp__dataLocal$OUT_READ >>
	     mod__regRead__0_resp__dataLocal$OUT_READ[4:0] ;
  assign ret__h30053 =
	     mod__regRead__1_resp__dataLocal$OUT_READ >>
	     mod__regRead__0_resp__dataLocal$OUT_READ[4:0] |
	     ~(32'hFFFFFFFF >>
	       mod__regRead__0_resp__dataLocal$OUT_READ[4:0]) &
	     {32{mod__regRead__1_resp__dataLocal$OUT_READ[31]}} ;
  assign ret__h30122 =
	     mod__regRead__0_resp__dataLocal$OUT_READ +
	     mod__regRead__1_resp__dataLocal$OUT_READ ;
  assign ret__h30154 =
	     mod__regRead__0_resp__dataLocal$OUT_READ -
	     mod__regRead__1_resp__dataLocal$OUT_READ ;
  assign ret__h30186 =
	     mod__regRead__0_resp__dataLocal$OUT_READ &
	     mod__regRead__1_resp__dataLocal$OUT_READ ;
  assign ret__h30218 =
	     mod__regRead__0_resp__dataLocal$OUT_READ |
	     mod__regRead__1_resp__dataLocal$OUT_READ ;
  assign ret__h30250 =
	     mod__regRead__0_resp__dataLocal$OUT_READ ^
	     mod__regRead__1_resp__dataLocal$OUT_READ ;
  assign ret__h30282 = ~ret__h30218 ;
  assign ret__h30326 =
	     ((mod__regRead__0_resp__dataLocal$OUT_READ ^ 32'h80000000) <
	      (mod__regRead__1_resp__dataLocal$OUT_READ ^ 32'h80000000)) ?
	       32'd1 :
	       32'd0 ;
  assign ret__h30362 =
	     (mod__regRead__0_resp__dataLocal$OUT_READ <
	      mod__regRead__1_resp__dataLocal$OUT_READ) ?
	       32'd1 :
	       32'd0 ;
  assign zimm__h20555 =
	     { 16'd0, mod__instQ__first__dataLocal$OUT_READ[15:0] } ;
  always@(mod__instQ__first__dataLocal$OUT_READ)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b000011: x__h20298 = 5'd31;
      6'b001001,
      6'b001010,
      6'b001011,
      6'b001100,
      6'b001101,
      6'b001110,
      6'b001111,
      6'b010000,
      6'b100011:
	  x__h20298 = mod__instQ__first__dataLocal$OUT_READ[20:16];
      default: x__h20298 = mod__instQ__first__dataLocal$OUT_READ[15:11];
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b0:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q1 =
	      mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b0 &&
	      mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b000010 &&
	      mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b000011 &&
	      mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b0;
      6'b000001, 6'b000110, 6'b000111:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q1 =
	      mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b0;
      6'b010000:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q1 =
	      mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b0 &&
	      mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b00100;
      default: CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q1 =
		   mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b0;
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ or
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q1)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b001001,
      6'b001010,
      6'b001011,
      6'b001100,
      6'b001101,
      6'b001110,
      6'b100011:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q2 =
	      mod__instQ__first__dataLocal$OUT_READ[25:21] != 5'b0;
      default: CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q2 =
		   mod__instQ__first__dataLocal$OUT_READ[31:26] !=
		   6'b001111 &&
		   mod__instQ__first__dataLocal$OUT_READ[31:26] !=
		   6'b000010 &&
		   mod__instQ__first__dataLocal$OUT_READ[31:26] !=
		   6'b000011 &&
		   CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q1;
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[5:0])
      6'b0, 6'b000010, 6'b000011:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q3 =
	      mod__instQ__first__dataLocal$OUT_READ[20:16] != 5'd0;
      default: CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q3 =
		   mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b001000 &&
		   mod__instQ__first__dataLocal$OUT_READ[5:0] != 6'b001001 &&
		   mod__instQ__first__dataLocal$OUT_READ[20:16] != 5'd0;
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b0:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q4 =
	      mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b0 ||
	      mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b000010 ||
	      mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b000011 ||
	      mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0;
      6'b000001, 6'b000110, 6'b000111:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q4 =
	      mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0;
      6'b010000:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q4 =
	      mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0 ||
	      mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b00100;
      default: CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q4 =
		   mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0;
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ or
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q4)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b001001,
      6'b001010,
      6'b001011,
      6'b001100,
      6'b001101,
      6'b001110,
      6'b100011:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d143 =
	      mod__instQ__first__dataLocal$OUT_READ[25:21] == 5'b0;
      default: IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d143 =
		   mod__instQ__first__dataLocal$OUT_READ[31:26] ==
		   6'b001111 ||
		   mod__instQ__first__dataLocal$OUT_READ[31:26] ==
		   6'b000010 ||
		   mod__instQ__first__dataLocal$OUT_READ[31:26] ==
		   6'b000011 ||
		   CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q4;
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[5:0])
      6'b0, 6'b000010, 6'b000011:
	  CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q5 =
	      mod__instQ__first__dataLocal$OUT_READ[20:16] == 5'd0;
      default: CASE_mod__instQ__first__dataLocalOUT_READ_BIT_ETC__q5 =
		   mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001000 ||
		   mod__instQ__first__dataLocal$OUT_READ[5:0] == 6'b001001 ||
		   mod__instQ__first__dataLocal$OUT_READ[20:16] == 5'd0;
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ or
	  mod__regRead__0_resp__dataLocal$OUT_READ or
	  mod__regRead__0_resp__dataLocal__read__92_EQ_m_ETC___d275 or
	  mod__regRead__0_resp__dataLocal__read__92_SLE_0___d280)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b000100:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d290 =
	      mod__regRead__0_resp__dataLocal__read__92_EQ_m_ETC___d275;
      6'b000101:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d290 =
	      !mod__regRead__0_resp__dataLocal__read__92_EQ_m_ETC___d275;
      6'b000110:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d290 =
	      mod__regRead__0_resp__dataLocal$OUT_READ == 32'd0 ||
	      mod__regRead__0_resp__dataLocal$OUT_READ[31];
      6'b000111:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d290 =
	      !mod__regRead__0_resp__dataLocal__read__92_SLE_0___d280;
      default: IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d290 =
		   !(mod__instQ__first__dataLocal$OUT_READ[20:16] == 5'd0 ^
		     mod__regRead__0_resp__dataLocal$OUT_READ[31]);
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ or
	  ret__h30362 or
	  ret__h29643 or
	  ret__h29753 or
	  ret__h29821 or
	  ret__h29890 or
	  ret__h29985 or
	  ret__h30053 or
	  ret__h30122 or
	  ret__h30154 or
	  ret__h30186 or
	  ret__h30218 or ret__h30250 or ret__h30282 or ret__h30326)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[5:0])
      6'b0:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h29643;
      6'b000010:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h29753;
      6'b000011:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h29821;
      6'b000100:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h29890;
      6'b000110:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h29985;
      6'b000111:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30053;
      6'b100001:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30122;
      6'b100011:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30154;
      6'b100100:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30186;
      6'b100101:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30218;
      6'b100110:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30250;
      6'b100111:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30282;
      6'b101010:
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
	      ret__h30326;
      default: IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 =
		   ret__h30362;
    endcase
  end
  always@(mod__instQ__first__dataLocal$OUT_READ or
	  IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261 or
	  ret__h20629 or
	  ret__h25269 or
	  ret__h25305 or
	  ret__h25341 or ret__h29484 or ret__h29516 or ret__h29548)
  begin
    case (mod__instQ__first__dataLocal$OUT_READ[31:26])
      6'b001001, 6'b100011, 6'b101011:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
	      ret__h20629;
      6'b001010:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
	      ret__h25269;
      6'b001011:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
	      ret__h25305;
      6'b001100:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
	      ret__h25341;
      6'b001101:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
	      ret__h29484;
      6'b001110:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
	      ret__h29516;
      6'b001111:
	  IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
	      ret__h29548;
      default: IF_mod__instQ__first__dataLocal__read_BITS_31__ETC___d269 =
		   IF_mod__instQ__first__dataLocal__read_BITS_5_T_ETC___d261;
    endcase
  end
endmodule  // mkExecute

