//
// Generated by Bluespec Compiler, version 2014.03.beta2 (build 33633, 2014-03-26)
//
// On Fri Nov 21 15:38:05 EST 2014
//
//
// Ports:
// Name                         I/O  size props
// read_0_resp_READ               O    32
// read_1_resp_READ               O    32
// CLK                            I     1 clock
// RST_N                          I     1 reset
// read_0_req_WRITE               I     5
// read_1_req_WRITE               I     5
// write_WRITE                    I    37
// read_0_req_EN_WRITE            I     1
// read_1_req_EN_WRITE            I     1
// write_EN_WRITE                 I     1
//
// Combinational paths from inputs to outputs:
//   (read_0_req_WRITE,
//    write_WRITE,
//    read_0_req_EN_WRITE,
//    write_EN_WRITE) -> read_0_resp_READ
//   (read_1_req_WRITE,
//    write_WRITE,
//    read_1_req_EN_WRITE,
//    write_EN_WRITE) -> read_1_resp_READ
//
//

`ifdef BSV_ASSIGNMENT_DELAY
`else
  `define BSV_ASSIGNMENT_DELAY
`endif

`ifdef BSV_POSITIVE_RESET
  `define BSV_RESET_VALUE 1'b1
  `define BSV_RESET_EDGE posedge
`else
  `define BSV_RESET_VALUE 1'b0
  `define BSV_RESET_EDGE negedge
`endif

module mkRegisters(CLK,
		   RST_N,

		   read_0_req_WRITE,
		   read_0_req_EN_WRITE,

		   read_0_resp_READ,

		   read_1_req_WRITE,
		   read_1_req_EN_WRITE,

		   read_1_resp_READ,

		   write_WRITE,
		   write_EN_WRITE);
  input  CLK;
  input  RST_N;

  // action method read_0_req_write
  input  [4 : 0] read_0_req_WRITE;
  input  read_0_req_EN_WRITE;

  // value method read_0_resp__read
  output [31 : 0] read_0_resp_READ;

  // action method read_1_req_write
  input  [4 : 0] read_1_req_WRITE;
  input  read_1_req_EN_WRITE;

  // value method read_1_resp__read
  output [31 : 0] read_1_resp_READ;

  // action method write_write
  input  [36 : 0] write_WRITE;
  input  write_EN_WRITE;

  // signals for module outputs
  wire [31 : 0] read_0_resp_READ, read_1_resp_READ;

  // ports of submodule mod__read__0_req__dataLocal
  wire [4 : 0] mod__read__0_req__dataLocal$IN_WRITE,
	       mod__read__0_req__dataLocal$OUT_READ;
  wire mod__read__0_req__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__read__0_req__enLocal
  wire mod__read__0_req__enLocal$IN_EN_WRITE;

  // ports of submodule mod__read__0_resp__dataLocal
  wire [31 : 0] mod__read__0_resp__dataLocal$IN_WRITE,
		mod__read__0_resp__dataLocal$OUT_READ;
  wire mod__read__0_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__read__1_req__dataLocal
  wire [4 : 0] mod__read__1_req__dataLocal$IN_WRITE,
	       mod__read__1_req__dataLocal$OUT_READ;
  wire mod__read__1_req__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__read__1_req__enLocal
  wire mod__read__1_req__enLocal$IN_EN_WRITE;

  // ports of submodule mod__read__1_resp__dataLocal
  wire [31 : 0] mod__read__1_resp__dataLocal$IN_WRITE,
		mod__read__1_resp__dataLocal$OUT_READ;
  wire mod__read__1_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__write__dataLocal
  wire [36 : 0] mod__write__dataLocal$IN_WRITE,
		mod__write__dataLocal$OUT_READ;
  wire mod__write__dataLocal$IN_EN_WRITE;

  // ports of submodule mod__write__enLocal
  wire mod__write__enLocal$IN_EN_WRITE, mod__write__enLocal$OUT_READ;

  // ports of submodule regs_mod__mod__read__0_req__dataLocal
  wire [4 : 0] regs_mod__mod__read__0_req__dataLocal$IN_WRITE,
	       regs_mod__mod__read__0_req__dataLocal$OUT_READ;
  wire regs_mod__mod__read__0_req__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__mod__read__0_req__enLocal
  wire regs_mod__mod__read__0_req__enLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__mod__read__0_resp__dataLocal
  wire [31 : 0] regs_mod__mod__read__0_resp__dataLocal$IN_WRITE,
		regs_mod__mod__read__0_resp__dataLocal$OUT_READ;
  wire regs_mod__mod__read__0_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__mod__read__1_req__dataLocal
  wire [4 : 0] regs_mod__mod__read__1_req__dataLocal$IN_WRITE,
	       regs_mod__mod__read__1_req__dataLocal$OUT_READ;
  wire regs_mod__mod__read__1_req__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__mod__read__1_req__enLocal
  wire regs_mod__mod__read__1_req__enLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__mod__read__1_resp__dataLocal
  wire [31 : 0] regs_mod__mod__read__1_resp__dataLocal$IN_WRITE,
		regs_mod__mod__read__1_resp__dataLocal$OUT_READ;
  wire regs_mod__mod__read__1_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__mod__write__0_dataLocal
  wire [36 : 0] regs_mod__mod__write__0_dataLocal$IN_WRITE,
		regs_mod__mod__write__0_dataLocal$OUT_READ;
  wire regs_mod__mod__write__0_dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__mod__write__0_enLocal
  wire regs_mod__mod__write__0_enLocal$IN_EN_WRITE,
       regs_mod__mod__write__0_enLocal$OUT_READ;

  // ports of submodule regs_mod__rf_0_0_mod__read__0_req__dataLocal
  wire [4 : 0] regs_mod__rf_0_0_mod__read__0_req__dataLocal$IN_WRITE,
	       regs_mod__rf_0_0_mod__read__0_req__dataLocal$OUT_READ;
  wire regs_mod__rf_0_0_mod__read__0_req__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_0_mod__read__0_req__enLocal
  wire regs_mod__rf_0_0_mod__read__0_req__enLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_0_mod__read__0_resp__dataLocal
  wire [31 : 0] regs_mod__rf_0_0_mod__read__0_resp__dataLocal$IN_WRITE,
		regs_mod__rf_0_0_mod__read__0_resp__dataLocal$OUT_READ;
  wire regs_mod__rf_0_0_mod__read__0_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_0_mod__write__0_dataLocal
  wire [36 : 0] regs_mod__rf_0_0_mod__write__0_dataLocal$IN_WRITE,
		regs_mod__rf_0_0_mod__write__0_dataLocal$OUT_READ;
  wire regs_mod__rf_0_0_mod__write__0_dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_0_mod__write__0_enLocal
  wire regs_mod__rf_0_0_mod__write__0_enLocal$IN_EN_WRITE,
       regs_mod__rf_0_0_mod__write__0_enLocal$OUT_READ;

  // ports of submodule regs_mod__rf_0_0_rf
  wire [31 : 0] regs_mod__rf_0_0_rf$READ_RESP_READ,
		regs_mod__rf_0_0_rf$WRITE_DATA_WRITE;
  wire [4 : 0] regs_mod__rf_0_0_rf$READ_REQ_WRITE,
	       regs_mod__rf_0_0_rf$WRITE_INDEX_WRITE;
  wire regs_mod__rf_0_0_rf$WRITE_EN_WRITE;

  // ports of submodule regs_mod__rf_0_1_mod__read__0_req__dataLocal
  wire [4 : 0] regs_mod__rf_0_1_mod__read__0_req__dataLocal$IN_WRITE,
	       regs_mod__rf_0_1_mod__read__0_req__dataLocal$OUT_READ;
  wire regs_mod__rf_0_1_mod__read__0_req__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_1_mod__read__0_req__enLocal
  wire regs_mod__rf_0_1_mod__read__0_req__enLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_1_mod__read__0_resp__dataLocal
  wire [31 : 0] regs_mod__rf_0_1_mod__read__0_resp__dataLocal$IN_WRITE,
		regs_mod__rf_0_1_mod__read__0_resp__dataLocal$OUT_READ;
  wire regs_mod__rf_0_1_mod__read__0_resp__dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_1_mod__write__0_dataLocal
  wire [36 : 0] regs_mod__rf_0_1_mod__write__0_dataLocal$IN_WRITE,
		regs_mod__rf_0_1_mod__write__0_dataLocal$OUT_READ;
  wire regs_mod__rf_0_1_mod__write__0_dataLocal$IN_EN_WRITE;

  // ports of submodule regs_mod__rf_0_1_mod__write__0_enLocal
  wire regs_mod__rf_0_1_mod__write__0_enLocal$IN_EN_WRITE,
       regs_mod__rf_0_1_mod__write__0_enLocal$OUT_READ;

  // ports of submodule regs_mod__rf_0_1_rf
  wire [31 : 0] regs_mod__rf_0_1_rf$READ_RESP_READ,
		regs_mod__rf_0_1_rf$WRITE_DATA_WRITE;
  wire [4 : 0] regs_mod__rf_0_1_rf$READ_REQ_WRITE,
	       regs_mod__rf_0_1_rf$WRITE_INDEX_WRITE;
  wire regs_mod__rf_0_1_rf$WRITE_EN_WRITE;

  // ports of submodule regs_mod__whichReg
  wire regs_mod__whichReg$IN_EN_WRITE;

  // remaining internal signals
  wire [31 : 0] IF_mod__write__enLocal__read__1_AND_mod__write_ETC___d28,
		IF_mod__write__enLocal__read__1_AND_mod__write_ETC___d35;

  // value method read_0_resp__read
  assign read_0_resp_READ = mod__read__0_resp__dataLocal$OUT_READ ;

  // value method read_1_resp__read
  assign read_1_resp_READ = mod__read__1_resp__dataLocal$OUT_READ ;

  // submodule mod__read__0_req__dataLocal
  mkWire #( /*width*/ 32'd5) mod__read__0_req__dataLocal(.IN_WRITE(mod__read__0_req__dataLocal$IN_WRITE),
							 .IN_EN_WRITE(mod__read__0_req__dataLocal$IN_EN_WRITE),
							 .OUT_READ(mod__read__0_req__dataLocal$OUT_READ));

  // submodule mod__read__0_req__enLocal
  mkPulse mod__read__0_req__enLocal(.IN_EN_WRITE(mod__read__0_req__enLocal$IN_EN_WRITE),
				    .OUT_READ());

  // submodule mod__read__0_resp__dataLocal
  mkWire #( /*width*/ 32'd32) mod__read__0_resp__dataLocal(.IN_WRITE(mod__read__0_resp__dataLocal$IN_WRITE),
							   .IN_EN_WRITE(mod__read__0_resp__dataLocal$IN_EN_WRITE),
							   .OUT_READ(mod__read__0_resp__dataLocal$OUT_READ));

  // submodule mod__read__1_req__dataLocal
  mkWire #( /*width*/ 32'd5) mod__read__1_req__dataLocal(.IN_WRITE(mod__read__1_req__dataLocal$IN_WRITE),
							 .IN_EN_WRITE(mod__read__1_req__dataLocal$IN_EN_WRITE),
							 .OUT_READ(mod__read__1_req__dataLocal$OUT_READ));

  // submodule mod__read__1_req__enLocal
  mkPulse mod__read__1_req__enLocal(.IN_EN_WRITE(mod__read__1_req__enLocal$IN_EN_WRITE),
				    .OUT_READ());

  // submodule mod__read__1_resp__dataLocal
  mkWire #( /*width*/ 32'd32) mod__read__1_resp__dataLocal(.IN_WRITE(mod__read__1_resp__dataLocal$IN_WRITE),
							   .IN_EN_WRITE(mod__read__1_resp__dataLocal$IN_EN_WRITE),
							   .OUT_READ(mod__read__1_resp__dataLocal$OUT_READ));

  // submodule mod__write__dataLocal
  mkWire #( /*width*/ 32'd37) mod__write__dataLocal(.IN_WRITE(mod__write__dataLocal$IN_WRITE),
						    .IN_EN_WRITE(mod__write__dataLocal$IN_EN_WRITE),
						    .OUT_READ(mod__write__dataLocal$OUT_READ));

  // submodule mod__write__enLocal
  mkPulse mod__write__enLocal(.IN_EN_WRITE(mod__write__enLocal$IN_EN_WRITE),
			      .OUT_READ(mod__write__enLocal$OUT_READ));

  // submodule regs_mod__mod__read__0_req__dataLocal
  mkWire #( /*width*/ 32'd5) regs_mod__mod__read__0_req__dataLocal(.IN_WRITE(regs_mod__mod__read__0_req__dataLocal$IN_WRITE),
								   .IN_EN_WRITE(regs_mod__mod__read__0_req__dataLocal$IN_EN_WRITE),
								   .OUT_READ(regs_mod__mod__read__0_req__dataLocal$OUT_READ));

  // submodule regs_mod__mod__read__0_req__enLocal
  mkPulse regs_mod__mod__read__0_req__enLocal(.IN_EN_WRITE(regs_mod__mod__read__0_req__enLocal$IN_EN_WRITE),
					      .OUT_READ());

  // submodule regs_mod__mod__read__0_resp__dataLocal
  mkWire #( /*width*/ 32'd32) regs_mod__mod__read__0_resp__dataLocal(.IN_WRITE(regs_mod__mod__read__0_resp__dataLocal$IN_WRITE),
								     .IN_EN_WRITE(regs_mod__mod__read__0_resp__dataLocal$IN_EN_WRITE),
								     .OUT_READ(regs_mod__mod__read__0_resp__dataLocal$OUT_READ));

  // submodule regs_mod__mod__read__1_req__dataLocal
  mkWire #( /*width*/ 32'd5) regs_mod__mod__read__1_req__dataLocal(.IN_WRITE(regs_mod__mod__read__1_req__dataLocal$IN_WRITE),
								   .IN_EN_WRITE(regs_mod__mod__read__1_req__dataLocal$IN_EN_WRITE),
								   .OUT_READ(regs_mod__mod__read__1_req__dataLocal$OUT_READ));

  // submodule regs_mod__mod__read__1_req__enLocal
  mkPulse regs_mod__mod__read__1_req__enLocal(.IN_EN_WRITE(regs_mod__mod__read__1_req__enLocal$IN_EN_WRITE),
					      .OUT_READ());

  // submodule regs_mod__mod__read__1_resp__dataLocal
  mkWire #( /*width*/ 32'd32) regs_mod__mod__read__1_resp__dataLocal(.IN_WRITE(regs_mod__mod__read__1_resp__dataLocal$IN_WRITE),
								     .IN_EN_WRITE(regs_mod__mod__read__1_resp__dataLocal$IN_EN_WRITE),
								     .OUT_READ(regs_mod__mod__read__1_resp__dataLocal$OUT_READ));

  // submodule regs_mod__mod__write__0_dataLocal
  mkWire #( /*width*/ 32'd37) regs_mod__mod__write__0_dataLocal(.IN_WRITE(regs_mod__mod__write__0_dataLocal$IN_WRITE),
								.IN_EN_WRITE(regs_mod__mod__write__0_dataLocal$IN_EN_WRITE),
								.OUT_READ(regs_mod__mod__write__0_dataLocal$OUT_READ));

  // submodule regs_mod__mod__write__0_enLocal
  mkPulse regs_mod__mod__write__0_enLocal(.IN_EN_WRITE(regs_mod__mod__write__0_enLocal$IN_EN_WRITE),
					  .OUT_READ(regs_mod__mod__write__0_enLocal$OUT_READ));

  // submodule regs_mod__rf_0_0_mod__read__0_req__dataLocal
  mkWire #( /*width*/ 32'd5) regs_mod__rf_0_0_mod__read__0_req__dataLocal(.IN_WRITE(regs_mod__rf_0_0_mod__read__0_req__dataLocal$IN_WRITE),
									  .IN_EN_WRITE(regs_mod__rf_0_0_mod__read__0_req__dataLocal$IN_EN_WRITE),
									  .OUT_READ(regs_mod__rf_0_0_mod__read__0_req__dataLocal$OUT_READ));

  // submodule regs_mod__rf_0_0_mod__read__0_req__enLocal
  mkPulse regs_mod__rf_0_0_mod__read__0_req__enLocal(.IN_EN_WRITE(regs_mod__rf_0_0_mod__read__0_req__enLocal$IN_EN_WRITE),
						     .OUT_READ());

  // submodule regs_mod__rf_0_0_mod__read__0_resp__dataLocal
  mkWire #( /*width*/ 32'd32) regs_mod__rf_0_0_mod__read__0_resp__dataLocal(.IN_WRITE(regs_mod__rf_0_0_mod__read__0_resp__dataLocal$IN_WRITE),
									    .IN_EN_WRITE(regs_mod__rf_0_0_mod__read__0_resp__dataLocal$IN_EN_WRITE),
									    .OUT_READ(regs_mod__rf_0_0_mod__read__0_resp__dataLocal$OUT_READ));

  // submodule regs_mod__rf_0_0_mod__write__0_dataLocal
  mkWire #( /*width*/ 32'd37) regs_mod__rf_0_0_mod__write__0_dataLocal(.IN_WRITE(regs_mod__rf_0_0_mod__write__0_dataLocal$IN_WRITE),
								       .IN_EN_WRITE(regs_mod__rf_0_0_mod__write__0_dataLocal$IN_EN_WRITE),
								       .OUT_READ(regs_mod__rf_0_0_mod__write__0_dataLocal$OUT_READ));

  // submodule regs_mod__rf_0_0_mod__write__0_enLocal
  mkPulse regs_mod__rf_0_0_mod__write__0_enLocal(.IN_EN_WRITE(regs_mod__rf_0_0_mod__write__0_enLocal$IN_EN_WRITE),
						 .OUT_READ(regs_mod__rf_0_0_mod__write__0_enLocal$OUT_READ));

  // submodule regs_mod__rf_0_0_rf
  mkRegFileVerilogLoad #( /*width*/ 32'd32,
			  /*n*/ 32'd5,
			  /*size*/ 32'd32,
			  /*file*/ "",
			  /*mode*/ 32'd0) regs_mod__rf_0_0_rf(.CLK(CLK),
							      .RST_N(RST_N),
							      .READ_REQ_WRITE(regs_mod__rf_0_0_rf$READ_REQ_WRITE),
							      .WRITE_DATA_WRITE(regs_mod__rf_0_0_rf$WRITE_DATA_WRITE),
							      .WRITE_INDEX_WRITE(regs_mod__rf_0_0_rf$WRITE_INDEX_WRITE),
							      .WRITE_EN_WRITE(regs_mod__rf_0_0_rf$WRITE_EN_WRITE),
							      .READ_RESP_READ(regs_mod__rf_0_0_rf$READ_RESP_READ));

  // submodule regs_mod__rf_0_1_mod__read__0_req__dataLocal
  mkWire #( /*width*/ 32'd5) regs_mod__rf_0_1_mod__read__0_req__dataLocal(.IN_WRITE(regs_mod__rf_0_1_mod__read__0_req__dataLocal$IN_WRITE),
									  .IN_EN_WRITE(regs_mod__rf_0_1_mod__read__0_req__dataLocal$IN_EN_WRITE),
									  .OUT_READ(regs_mod__rf_0_1_mod__read__0_req__dataLocal$OUT_READ));

  // submodule regs_mod__rf_0_1_mod__read__0_req__enLocal
  mkPulse regs_mod__rf_0_1_mod__read__0_req__enLocal(.IN_EN_WRITE(regs_mod__rf_0_1_mod__read__0_req__enLocal$IN_EN_WRITE),
						     .OUT_READ());

  // submodule regs_mod__rf_0_1_mod__read__0_resp__dataLocal
  mkWire #( /*width*/ 32'd32) regs_mod__rf_0_1_mod__read__0_resp__dataLocal(.IN_WRITE(regs_mod__rf_0_1_mod__read__0_resp__dataLocal$IN_WRITE),
									    .IN_EN_WRITE(regs_mod__rf_0_1_mod__read__0_resp__dataLocal$IN_EN_WRITE),
									    .OUT_READ(regs_mod__rf_0_1_mod__read__0_resp__dataLocal$OUT_READ));

  // submodule regs_mod__rf_0_1_mod__write__0_dataLocal
  mkWire #( /*width*/ 32'd37) regs_mod__rf_0_1_mod__write__0_dataLocal(.IN_WRITE(regs_mod__rf_0_1_mod__write__0_dataLocal$IN_WRITE),
								       .IN_EN_WRITE(regs_mod__rf_0_1_mod__write__0_dataLocal$IN_EN_WRITE),
								       .OUT_READ(regs_mod__rf_0_1_mod__write__0_dataLocal$OUT_READ));

  // submodule regs_mod__rf_0_1_mod__write__0_enLocal
  mkPulse regs_mod__rf_0_1_mod__write__0_enLocal(.IN_EN_WRITE(regs_mod__rf_0_1_mod__write__0_enLocal$IN_EN_WRITE),
						 .OUT_READ(regs_mod__rf_0_1_mod__write__0_enLocal$OUT_READ));

  // submodule regs_mod__rf_0_1_rf
  mkRegFileVerilogLoad #( /*width*/ 32'd32,
			  /*n*/ 32'd5,
			  /*size*/ 32'd32,
			  /*file*/ "",
			  /*mode*/ 32'd0) regs_mod__rf_0_1_rf(.CLK(CLK),
							      .RST_N(RST_N),
							      .READ_REQ_WRITE(regs_mod__rf_0_1_rf$READ_REQ_WRITE),
							      .WRITE_DATA_WRITE(regs_mod__rf_0_1_rf$WRITE_DATA_WRITE),
							      .WRITE_INDEX_WRITE(regs_mod__rf_0_1_rf$WRITE_INDEX_WRITE),
							      .WRITE_EN_WRITE(regs_mod__rf_0_1_rf$WRITE_EN_WRITE),
							      .READ_RESP_READ(regs_mod__rf_0_1_rf$READ_RESP_READ));

  // submodule regs_mod__whichReg
  mkReg #( /*width*/ 32'd0) regs_mod__whichReg(.CLK(CLK),
					       .RST_N(RST_N),
					       .IN_EN_WRITE(regs_mod__whichReg$IN_EN_WRITE));

  // submodule mod__read__0_req__dataLocal
  assign mod__read__0_req__dataLocal$IN_WRITE = read_0_req_WRITE ;
  assign mod__read__0_req__dataLocal$IN_EN_WRITE = read_0_req_EN_WRITE ;

  // submodule mod__read__0_req__enLocal
  assign mod__read__0_req__enLocal$IN_EN_WRITE = read_0_req_EN_WRITE ;

  // submodule mod__read__0_resp__dataLocal
  assign mod__read__0_resp__dataLocal$IN_WRITE =
	     (mod__read__0_req__dataLocal$OUT_READ == 5'd0) ?
	       32'd0 :
	       IF_mod__write__enLocal__read__1_AND_mod__write_ETC___d28 ;
  assign mod__read__0_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__read__1_req__dataLocal
  assign mod__read__1_req__dataLocal$IN_WRITE = read_1_req_WRITE ;
  assign mod__read__1_req__dataLocal$IN_EN_WRITE = read_1_req_EN_WRITE ;

  // submodule mod__read__1_req__enLocal
  assign mod__read__1_req__enLocal$IN_EN_WRITE = read_1_req_EN_WRITE ;

  // submodule mod__read__1_resp__dataLocal
  assign mod__read__1_resp__dataLocal$IN_WRITE =
	     (mod__read__1_req__dataLocal$OUT_READ == 5'd0) ?
	       32'd0 :
	       IF_mod__write__enLocal__read__1_AND_mod__write_ETC___d35 ;
  assign mod__read__1_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule mod__write__dataLocal
  assign mod__write__dataLocal$IN_WRITE = write_WRITE ;
  assign mod__write__dataLocal$IN_EN_WRITE = write_EN_WRITE ;

  // submodule mod__write__enLocal
  assign mod__write__enLocal$IN_EN_WRITE = write_EN_WRITE ;

  // submodule regs_mod__mod__read__0_req__dataLocal
  assign regs_mod__mod__read__0_req__dataLocal$IN_WRITE =
	     mod__read__0_req__dataLocal$OUT_READ ;
  assign regs_mod__mod__read__0_req__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__mod__read__0_req__enLocal
  assign regs_mod__mod__read__0_req__enLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__mod__read__0_resp__dataLocal
  assign regs_mod__mod__read__0_resp__dataLocal$IN_WRITE =
	     regs_mod__rf_0_0_mod__read__0_resp__dataLocal$OUT_READ ;
  assign regs_mod__mod__read__0_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__mod__read__1_req__dataLocal
  assign regs_mod__mod__read__1_req__dataLocal$IN_WRITE =
	     mod__read__1_req__dataLocal$OUT_READ ;
  assign regs_mod__mod__read__1_req__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__mod__read__1_req__enLocal
  assign regs_mod__mod__read__1_req__enLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__mod__read__1_resp__dataLocal
  assign regs_mod__mod__read__1_resp__dataLocal$IN_WRITE =
	     regs_mod__rf_0_1_mod__read__0_resp__dataLocal$OUT_READ ;
  assign regs_mod__mod__read__1_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__mod__write__0_dataLocal
  assign regs_mod__mod__write__0_dataLocal$IN_WRITE =
	     mod__write__dataLocal$OUT_READ ;
  assign regs_mod__mod__write__0_dataLocal$IN_EN_WRITE =
	     mod__write__enLocal$OUT_READ &&
	     mod__write__dataLocal$OUT_READ[36:32] != 5'd0 ;

  // submodule regs_mod__mod__write__0_enLocal
  assign regs_mod__mod__write__0_enLocal$IN_EN_WRITE =
	     mod__write__enLocal$OUT_READ &&
	     mod__write__dataLocal$OUT_READ[36:32] != 5'd0 ;

  // submodule regs_mod__rf_0_0_mod__read__0_req__dataLocal
  assign regs_mod__rf_0_0_mod__read__0_req__dataLocal$IN_WRITE =
	     regs_mod__mod__read__0_req__dataLocal$OUT_READ ;
  assign regs_mod__rf_0_0_mod__read__0_req__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__rf_0_0_mod__read__0_req__enLocal
  assign regs_mod__rf_0_0_mod__read__0_req__enLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__rf_0_0_mod__read__0_resp__dataLocal
  assign regs_mod__rf_0_0_mod__read__0_resp__dataLocal$IN_WRITE =
	     regs_mod__rf_0_0_rf$READ_RESP_READ ;
  assign regs_mod__rf_0_0_mod__read__0_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__rf_0_0_mod__write__0_dataLocal
  assign regs_mod__rf_0_0_mod__write__0_dataLocal$IN_WRITE =
	     regs_mod__mod__write__0_dataLocal$OUT_READ ;
  assign regs_mod__rf_0_0_mod__write__0_dataLocal$IN_EN_WRITE =
	     regs_mod__mod__write__0_enLocal$OUT_READ ;

  // submodule regs_mod__rf_0_0_mod__write__0_enLocal
  assign regs_mod__rf_0_0_mod__write__0_enLocal$IN_EN_WRITE =
	     regs_mod__mod__write__0_enLocal$OUT_READ ;

  // submodule regs_mod__rf_0_0_rf
  assign regs_mod__rf_0_0_rf$READ_REQ_WRITE =
	     regs_mod__rf_0_0_mod__read__0_req__dataLocal$OUT_READ ;
  assign regs_mod__rf_0_0_rf$WRITE_DATA_WRITE =
	     regs_mod__rf_0_0_mod__write__0_dataLocal$OUT_READ[31:0] ;
  assign regs_mod__rf_0_0_rf$WRITE_INDEX_WRITE =
	     regs_mod__rf_0_0_mod__write__0_dataLocal$OUT_READ[36:32] ;
  assign regs_mod__rf_0_0_rf$WRITE_EN_WRITE =
	     regs_mod__rf_0_0_mod__write__0_enLocal$OUT_READ ;

  // submodule regs_mod__rf_0_1_mod__read__0_req__dataLocal
  assign regs_mod__rf_0_1_mod__read__0_req__dataLocal$IN_WRITE =
	     regs_mod__mod__read__1_req__dataLocal$OUT_READ ;
  assign regs_mod__rf_0_1_mod__read__0_req__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__rf_0_1_mod__read__0_req__enLocal
  assign regs_mod__rf_0_1_mod__read__0_req__enLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__rf_0_1_mod__read__0_resp__dataLocal
  assign regs_mod__rf_0_1_mod__read__0_resp__dataLocal$IN_WRITE =
	     regs_mod__rf_0_1_rf$READ_RESP_READ ;
  assign regs_mod__rf_0_1_mod__read__0_resp__dataLocal$IN_EN_WRITE = 1'd1 ;

  // submodule regs_mod__rf_0_1_mod__write__0_dataLocal
  assign regs_mod__rf_0_1_mod__write__0_dataLocal$IN_WRITE =
	     regs_mod__mod__write__0_dataLocal$OUT_READ ;
  assign regs_mod__rf_0_1_mod__write__0_dataLocal$IN_EN_WRITE =
	     regs_mod__mod__write__0_enLocal$OUT_READ ;

  // submodule regs_mod__rf_0_1_mod__write__0_enLocal
  assign regs_mod__rf_0_1_mod__write__0_enLocal$IN_EN_WRITE =
	     regs_mod__mod__write__0_enLocal$OUT_READ ;

  // submodule regs_mod__rf_0_1_rf
  assign regs_mod__rf_0_1_rf$READ_REQ_WRITE =
	     regs_mod__rf_0_1_mod__read__0_req__dataLocal$OUT_READ ;
  assign regs_mod__rf_0_1_rf$WRITE_DATA_WRITE =
	     regs_mod__rf_0_1_mod__write__0_dataLocal$OUT_READ[31:0] ;
  assign regs_mod__rf_0_1_rf$WRITE_INDEX_WRITE =
	     regs_mod__rf_0_1_mod__write__0_dataLocal$OUT_READ[36:32] ;
  assign regs_mod__rf_0_1_rf$WRITE_EN_WRITE =
	     regs_mod__rf_0_1_mod__write__0_enLocal$OUT_READ ;

  // submodule regs_mod__whichReg
  assign regs_mod__whichReg$IN_EN_WRITE = 1'd1 ;

  // remaining internal signals
  assign IF_mod__write__enLocal__read__1_AND_mod__write_ETC___d28 =
	     (mod__write__enLocal$OUT_READ &&
	      mod__write__dataLocal$OUT_READ[36:32] ==
	      mod__read__0_req__dataLocal$OUT_READ) ?
	       mod__write__dataLocal$OUT_READ[31:0] :
	       regs_mod__mod__read__0_resp__dataLocal$OUT_READ ;
  assign IF_mod__write__enLocal__read__1_AND_mod__write_ETC___d35 =
	     (mod__write__enLocal$OUT_READ &&
	      mod__write__dataLocal$OUT_READ[36:32] ==
	      mod__read__1_req__dataLocal$OUT_READ) ?
	       mod__write__dataLocal$OUT_READ[31:0] :
	       regs_mod__mod__read__1_resp__dataLocal$OUT_READ ;
endmodule  // mkRegisters

